<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Category
 * @package App
 */
class Category extends Model
{
    /**
     * @var bool
     */
    public $timestamps = false;

    /**
     * @var array
     */
    protected $fillable = ['title','id'];

    /**
     * @return HasMany
     */
    public function albums(): HasMany
    {
        return $this->hasMany(Album::class, 'category_id' , 'id');
    }

    public function delete()
    {
        // кароч хуйня, надо писать обсервер все таки
        // ну типа они сами на сайте у себя пишут мол есть такое и наш парсер это умеет, но все таблицы отклоняют такие запросы(((
        // типикал yagni проеб
        //эх, прийдется все таки ивент пилить?
        // ну или типа сделть тут до удаления, типа апдейт по всем альбомам, это быстрее но варик так себе
        // можешь пока что бы быстрее сделать тут бахнуть и ебни тудушку себе, отрефакторить в будущем
        // Можно по сути типа агрегата что то сделать но тоже так себе варик, кароче
        return parent::delete(); // TODO: Change the autogenerated stub
    }


}
